apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: argocd
resources:
- namespace.yaml
- https://raw.githubusercontent.com/argoproj/argo-cd/v2.3.3/manifests/ha/install.yaml
- ingress.yaml
- argo-repo-pvc.yaml
patchesStrategicMerge:
- argo-repo-server.yaml
