# kustomization.yaml
bases:
- github.com/kubernetes/ingress-nginx/deploy/static/provider/baremetal?ref=controller-v1.1.3
resources:
- configs/tcp-services.yaml
- configs/udp-services.yaml
patchesStrategicMerge:
- configs/nginx-conf.yaml
patchesJson6902:
- target:
    group: ''
    version: v1
    kind: Service
    name: ingress-nginx-controller
  path: service.yaml
- target:
    kind: Deployment
    name: ingress-nginx-controller
  path: deployment.yaml
