apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: harbor-registry
  namespace: default
spec:
  encryptedData:
    .dockerconfigjson: AgCR4BgqswAFlAHl43eXB8y4pagmJ4RJ8ZFFWX4Fqe7iHWFcAK5mtafpESjAumntnJZxlDadN663HhNXgd1eesp+nEBWTLcrHIXLDd2rwfyG2q54G2cIL03CSRN1GnfrdEC8NeDhvaXK2Bf9NdjqZhDgHIpzZf/2AhngE/AF13kkkXCbzvNHrQT/ycqRrEgLZd6a7KiMdjRuFQ8F+Md5Yod4/oAr1O1/5HTioHLJH++WXVcYrbOAJhoWEvycxaObi+87R4Epz6Qp2wcLpja9z3KiASuyovtIpJyUYRidiLXVLgzb8HGOaJCytIYACx4WfvXrUJ+UyjceV5PGMge0CX0+nGzXp8cjc6twrmKf7KjBXl7EhJo4k+rJJxqdvq69qduDXy9yBGj+D3fe7sCCJUJvlh60KARhfbMesoCFCD9feyQbJPEAVi0AQpfsKo77LuwdBVbxgJm0KorG7YFInNEa6eH54JH0wEQZ9mJsMPTUxX8eQxOYMDMzbHA8yhP8ddK+e2IOUI8y9gCrNAU8Hq9uKARZtwIhtBxeV6+NuX5QtGevUP+zhlFp4Qq3C2M0pWrBwdm01jv3ZoBkFVhuTL0qwPbrHAoooMYj4xlEGN7czpzxAtLRGaoeCL8lSdoInHRPGtf2fnT1vEDIjCTOf11OjBsFmw9dvlPiq/5ZS3gkCnT/hhPHvCgQsEdxCHs7iAIezmrWejpfM4Q4sdYrJHjh130wCBrVaTif2u1tOrLK1i3j0E2Qyw15ncNPsO2LQ/8Sy0tTUX0SOk56Vo1NfoATyUPltEKVA1xAZd3XdvP66Fok1kwlEo6dElUQ1ljcWm9+sHjLs3Xx5Ksu2OgReXqkLZuYKiYztTKF1kV3/MpHMsI8ZC6RMhc7dg==
  template:
    data: null
    metadata:
      creationTimestamp: null
      name: harbor-registry
      namespace: default
    type: kubernetes.io/dockerconfigjson

