apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: root-signed-certificate
  namespace: default
spec:
  isCA: true
  dnsNames:
    - rancher-demo.monach.us
  secretName: root-secret
  privateKey:
    algorithm: ECDSA
    size: 256
  issuerRef:
    name: selfsigned-issuer
    kind: ClusterIssuer
    group: cert-manager.io
---
apiVersion: cert-manager.io/v1
kind: Issuer
metadata:
  name: demo-ca-issuer
  namespace: default
spec:
  ca:
    secretName: root-secret